name: Manual
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'input name'
        required: true
      
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: ${{ inputs.environment }}
